package main

import (
	"fmt"
	"go_project/syntax"
)

func main() {
	fmt.Println("--------------------------------------------")
	fmt.Println("Above the output of the all the Syntax file ")
	fmt.Println("--------------------------------------------")
	syntax.Hello()
	fmt.Println("--------------------------------------------")
	syntax.ValueDemo()
	fmt.Println("--------------------------------------------")
	syntax.VariablesDemo()
	fmt.Println("------------------------------------------")
	syntax.LoopDemo()
	fmt.Println("------------------------------------------")
	syntax.IfElseDemo()
	fmt.Println("------------------------------------------")
	syntax.SwitchDemo()
	fmt.Println("------------------------------------------")
	syntax.ArraysDemo()
	fmt.Println("-----------------------------------------")
	syntax.SlicesDemo()
	fmt.Println("-----------------------------------------")
	syntax.MapsDemo()
	fmt.Println("----------------------------------------")
	syntax.Day1()
	fmt.Println("---------------------------------------")
	res := syntax.FunctionDemo()
	fmt.Println(res)
	fmt.Println("---------------------------------------")
	res2:= syntax.Func2Demo(44,55)
	fmt.Println(res2)
	fmt.Println("---------------------------------------") 
	x,y,z:=syntax.FuncWithMultiReturnValue(3,4,5)
	fmt.Println(x,y,z)
	fmt.Println("--------------------------------------")
	fmt.Println(syntax.VariableArgumentFunc(3,4,5,6,7,8,9))
	fmt.Println("--------------------------------------")
	fmt.Println(syntax.IntSeq())
	fmt.Println(syntax.IntSeq())
	fmt.Println("--------------------------------------")
	syntax.RangeFuncArr()
	fmt.Println("--------------------------------------")
	syntax.ImediateFunc()
	fmt.Println("--------------------------------------")
	syntax.AnonomousFunc()
	fmt.Println("--------------------------------------")
	counter:=syntax.CountClosures()
	fmt.Println(counter())
	fmt.Println(counter())
	fmt.Println(counter())
	fmt.Println("--------------------------------------")
	sum := syntax.FunctionAsArguement(3, 4, func(x, y int) int {
		return x * y
	})
	fmt.Println(sum)
	fmt.Println("----------------------------------------")
	result , errors:=syntax.ZeroDevisionError(55,0)
	fmt.Println(result,errors)
	fmt.Println("--------------------------------------")
	syntax.PointerDemo()
	fmt.Println("--------------------------------------")
	syntax.PointerExamples()
	fmt.Println("-------------------------------------")
	syntax.Ferson()
	fmt.Println("-----------------------------------")
	syntax.GorouteRunner()
	fmt.Println("-----------------------------------")
}